- name: Create a jenkins job using basic authentication
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/s-pipeline.xml') }}"
    name: test
    password: 114d17516f4cb0f93ab764658b798303df
    #password: admin123
    url: http://172.31.12.174:8080
    user: admin
